"""
Comprehensive skills database.
Each entry: canonical name, list of aliases/variants, category.
The matcher builds a case-insensitive alias → canonical lookup.
"""

SKILLS = [
    # ─── Programming Languages ────────────────────────────────────────────
    {"name": "Python",         "aliases": ["python3", "python 3", "py"],                                       "category": "Programming Languages"},
    {"name": "JavaScript",     "aliases": ["js", "java script", "ecmascript", "es6", "es2015", "es2016", "es2017", "es2018", "es2019", "es2020"],  "category": "Programming Languages"},
    {"name": "TypeScript",     "aliases": ["ts", "typescript"],                                                "category": "Programming Languages"},
    {"name": "Java",           "aliases": ["java se", "java ee", "jdk", "jvm"],                               "category": "Programming Languages"},
    {"name": "C",              "aliases": ["c programming", "c language", "ansi c"],                          "category": "Programming Languages"},
    {"name": "C++",            "aliases": ["cpp", "c plus plus", "c++11", "c++14", "c++17", "c++20"],         "category": "Programming Languages"},
    {"name": "C#",             "aliases": ["csharp", "c sharp", "dotnet c#", ".net c#"],                      "category": "Programming Languages"},
    {"name": "Go",             "aliases": ["golang", "go lang"],                                               "category": "Programming Languages"},
    {"name": "Rust",           "aliases": ["rust lang", "rustlang"],                                          "category": "Programming Languages"},
    {"name": "Swift",          "aliases": ["swift 5", "swift programming"],                                   "category": "Programming Languages"},
    {"name": "Kotlin",         "aliases": ["kotlin lang"],                                                     "category": "Programming Languages"},
    {"name": "Scala",          "aliases": ["scala lang"],                                                      "category": "Programming Languages"},
    {"name": "Ruby",           "aliases": ["ruby lang", "rb"],                                                 "category": "Programming Languages"},
    {"name": "PHP",            "aliases": ["php7", "php8", "php programming"],                                "category": "Programming Languages"},
    {"name": "R",              "aliases": ["r programming", "r language", "r stats"],                         "category": "Programming Languages"},
    {"name": "MATLAB",         "aliases": ["matlab programming"],                                              "category": "Programming Languages"},
    {"name": "Perl",           "aliases": ["perl scripting"],                                                  "category": "Programming Languages"},
    {"name": "Haskell",        "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Elixir",         "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Erlang",         "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Dart",           "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Julia",          "aliases": ["julia lang"],                                                      "category": "Programming Languages"},
    {"name": "Lua",            "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Groovy",         "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Shell Scripting","aliases": ["bash", "shell script", "bash scripting", "sh", "zsh", "ksh"],     "category": "Programming Languages"},
    {"name": "PowerShell",     "aliases": ["powershell scripting", "ps1"],                                    "category": "Programming Languages"},
    {"name": "Assembly",       "aliases": ["asm", "assembly language", "x86 assembly", "arm assembly"],       "category": "Programming Languages"},
    {"name": "VHDL",           "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Verilog",        "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Prolog",         "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Clojure",        "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "F#",             "aliases": ["fsharp", "f sharp"],                                              "category": "Programming Languages"},
    {"name": "OCaml",          "aliases": [],                                                                  "category": "Programming Languages"},
    {"name": "Objective-C",    "aliases": ["objc", "objective c"],                                            "category": "Programming Languages"},

    # ─── Web Frontend ─────────────────────────────────────────────────────
    {"name": "React",          "aliases": ["reactjs", "react.js", "react js"],                                "category": "Web Development"},
    {"name": "Angular",        "aliases": ["angularjs", "angular.js", "angular 2", "angular 14", "angular 15", "angular 16", "ng"],  "category": "Web Development"},
    {"name": "Vue.js",         "aliases": ["vue", "vuejs", "vue 3", "vue 2"],                                 "category": "Web Development"},
    {"name": "Next.js",        "aliases": ["nextjs", "next js"],                                              "category": "Web Development"},
    {"name": "Nuxt.js",        "aliases": ["nuxt", "nuxtjs"],                                                 "category": "Web Development"},
    {"name": "Svelte",         "aliases": ["sveltejs"],                                                        "category": "Web Development"},
    {"name": "Remix",          "aliases": [],                                                                  "category": "Web Development"},
    {"name": "Gatsby",         "aliases": ["gatsbyjs"],                                                        "category": "Web Development"},
    {"name": "HTML",           "aliases": ["html5", "html 5", "hypertext markup"],                            "category": "Web Development"},
    {"name": "CSS",            "aliases": ["css3", "css 3", "cascading style sheets"],                        "category": "Web Development"},
    {"name": "Tailwind CSS",   "aliases": ["tailwind", "tailwindcss"],                                        "category": "Web Development"},
    {"name": "Bootstrap",      "aliases": ["bootstrap 5", "bootstrap 4"],                                     "category": "Web Development"},
    {"name": "SASS",           "aliases": ["scss", "sass/scss"],                                              "category": "Web Development"},
    {"name": "Redux",          "aliases": ["redux toolkit", "react redux"],                                   "category": "Web Development"},
    {"name": "GraphQL",        "aliases": ["graph ql"],                                                        "category": "Web Development"},
    {"name": "REST API",       "aliases": ["rest", "restful", "restful api", "rest apis", "http api"],        "category": "Web Development"},
    {"name": "WebSocket",      "aliases": ["websockets", "ws"],                                               "category": "Web Development"},
    {"name": "jQuery",         "aliases": ["jquery"],                                                          "category": "Web Development"},
    {"name": "Webpack",        "aliases": [],                                                                  "category": "Web Development"},
    {"name": "Vite",           "aliases": ["vitejs"],                                                          "category": "Web Development"},
    {"name": "Babel",          "aliases": [],                                                                  "category": "Web Development"},
    {"name": "Three.js",       "aliases": ["threejs"],                                                         "category": "Web Development"},
    {"name": "D3.js",          "aliases": ["d3", "d3js"],                                                     "category": "Web Development"},

    # ─── Backend / Frameworks ─────────────────────────────────────────────
    {"name": "Node.js",        "aliases": ["node", "nodejs"],                                                  "category": "Web Development"},
    {"name": "Express.js",     "aliases": ["express", "expressjs"],                                           "category": "Web Development"},
    {"name": "Django",         "aliases": ["django rest framework", "drf"],                                   "category": "Web Development"},
    {"name": "Flask",          "aliases": ["flask python"],                                                    "category": "Web Development"},
    {"name": "FastAPI",        "aliases": ["fast api"],                                                        "category": "Web Development"},
    {"name": "Spring Boot",    "aliases": ["spring", "spring framework", "spring mvc", "spring security"],    "category": "Web Development"},
    {"name": "Laravel",        "aliases": [],                                                                  "category": "Web Development"},
    {"name": "Ruby on Rails",  "aliases": ["rails", "ror"],                                                   "category": "Web Development"},
    {"name": "ASP.NET",        "aliases": ["asp.net core", "aspnet", ".net core", "dotnet"],                  "category": "Web Development"},
    {"name": "NestJS",         "aliases": ["nestjs", "nest.js"],                                              "category": "Web Development"},
    {"name": "Gin",            "aliases": ["gin framework", "gin golang"],                                    "category": "Web Development"},
    {"name": "Echo",           "aliases": ["echo framework"],                                                  "category": "Web Development"},
    {"name": "Fiber",          "aliases": ["fiber framework"],                                                 "category": "Web Development"},
    {"name": "Actix",          "aliases": ["actix web"],                                                       "category": "Web Development"},
    {"name": "gRPC",           "aliases": ["grpc", "protocol buffers", "protobuf"],                           "category": "Web Development"},
    {"name": "Microservices",  "aliases": ["microservice architecture", "micro services"],                    "category": "Web Development"},
    {"name": "Serverless",     "aliases": ["serverless framework", "faas"],                                   "category": "Web Development"},

    # ─── Mobile ───────────────────────────────────────────────────────────
    {"name": "React Native",   "aliases": ["react-native", "rn"],                                             "category": "Mobile Development"},
    {"name": "Flutter",        "aliases": ["flutter dart"],                                                    "category": "Mobile Development"},
    {"name": "Android",        "aliases": ["android development", "android sdk"],                             "category": "Mobile Development"},
    {"name": "iOS",            "aliases": ["ios development", "ios sdk"],                                     "category": "Mobile Development"},
    {"name": "Ionic",          "aliases": [],                                                                  "category": "Mobile Development"},
    {"name": "Xamarin",        "aliases": [],                                                                  "category": "Mobile Development"},
    {"name": "Jetpack Compose","aliases": ["compose", "android compose"],                                     "category": "Mobile Development"},
    {"name": "SwiftUI",        "aliases": [],                                                                  "category": "Mobile Development"},

    # ─── Databases ────────────────────────────────────────────────────────
    {"name": "MySQL",          "aliases": ["mysql database"],                                                  "category": "Databases"},
    {"name": "PostgreSQL",     "aliases": ["postgres", "postgresql", "psql"],                                 "category": "Databases"},
    {"name": "SQLite",         "aliases": [],                                                                  "category": "Databases"},
    {"name": "Microsoft SQL Server", "aliases": ["mssql", "sql server", "t-sql", "tsql"],                    "category": "Databases"},
    {"name": "Oracle DB",      "aliases": ["oracle database", "oracle", "pl/sql", "plsql"],                  "category": "Databases"},
    {"name": "MongoDB",        "aliases": ["mongo", "mongodb atlas"],                                         "category": "Databases"},
    {"name": "Redis",          "aliases": ["redis cache"],                                                     "category": "Databases"},
    {"name": "Cassandra",      "aliases": ["apache cassandra"],                                               "category": "Databases"},
    {"name": "DynamoDB",       "aliases": ["aws dynamodb"],                                                   "category": "Databases"},
    {"name": "Firebase",       "aliases": ["firebase realtime", "cloud firestore", "firestore"],              "category": "Databases"},
    {"name": "Elasticsearch",  "aliases": ["elastic search", "elasticsearch kibana"],                         "category": "Databases"},
    {"name": "Neo4j",          "aliases": ["neo4j graph"],                                                    "category": "Databases"},
    {"name": "CouchDB",        "aliases": [],                                                                  "category": "Databases"},
    {"name": "InfluxDB",       "aliases": [],                                                                  "category": "Databases"},
    {"name": "Snowflake",      "aliases": [],                                                                  "category": "Databases"},
    {"name": "BigQuery",       "aliases": ["google bigquery"],                                                "category": "Databases"},
    {"name": "Redshift",       "aliases": ["aws redshift"],                                                   "category": "Databases"},
    {"name": "SQL",            "aliases": ["structured query language", "sql queries", "advanced sql"],       "category": "Databases"},
    {"name": "NoSQL",          "aliases": [],                                                                  "category": "Databases"},
    {"name": "Hive",           "aliases": ["apache hive", "hiveql"],                                         "category": "Databases"},
    {"name": "HBase",          "aliases": [],                                                                  "category": "Databases"},
    {"name": "Supabase",       "aliases": [],                                                                  "category": "Databases"},
    {"name": "PrismaORM",      "aliases": ["prisma", "prisma orm"],                                          "category": "Databases"},
    {"name": "Mongoose",       "aliases": [],                                                                  "category": "Databases"},
    {"name": "SQLAlchemy",     "aliases": [],                                                                  "category": "Databases"},
    {"name": "Hibernate",      "aliases": ["jpa", "java persistence api"],                                   "category": "Databases"},

    # ─── Cloud Platforms ──────────────────────────────────────────────────
    {"name": "AWS",            "aliases": ["amazon web services", "amazon aws"],                              "category": "Cloud & DevOps"},
    {"name": "Google Cloud",   "aliases": ["gcp", "google cloud platform"],                                  "category": "Cloud & DevOps"},
    {"name": "Microsoft Azure","aliases": ["azure", "ms azure"],                                              "category": "Cloud & DevOps"},
    {"name": "AWS Lambda",     "aliases": ["lambda functions"],                                               "category": "Cloud & DevOps"},
    {"name": "AWS EC2",        "aliases": ["ec2"],                                                            "category": "Cloud & DevOps"},
    {"name": "AWS S3",         "aliases": ["s3", "amazon s3"],                                               "category": "Cloud & DevOps"},
    {"name": "AWS EKS",        "aliases": ["elastic kubernetes service"],                                     "category": "Cloud & DevOps"},
    {"name": "AWS RDS",        "aliases": ["rds"],                                                            "category": "Cloud & DevOps"},
    {"name": "AWS SQS",        "aliases": ["sqs"],                                                            "category": "Cloud & DevOps"},
    {"name": "CloudFormation", "aliases": ["aws cloudformation"],                                             "category": "Cloud & DevOps"},
    {"name": "Heroku",         "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "DigitalOcean",   "aliases": ["digital ocean"],                                                  "category": "Cloud & DevOps"},
    {"name": "Vercel",         "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Netlify",        "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Cloudflare",     "aliases": [],                                                                  "category": "Cloud & DevOps"},

    # ─── DevOps & Infrastructure ─────────────────────────────────────────
    {"name": "Docker",         "aliases": ["docker container", "dockerfile", "docker compose", "docker-compose"], "category": "Cloud & DevOps"},
    {"name": "Kubernetes",     "aliases": ["k8s", "kube", "kubectl"],                                        "category": "Cloud & DevOps"},
    {"name": "Terraform",      "aliases": ["terraform iac", "infrastructure as code"],                       "category": "Cloud & DevOps"},
    {"name": "Ansible",        "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Puppet",         "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Chef",           "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Jenkins",        "aliases": ["jenkins ci", "jenkins pipeline"],                                 "category": "Cloud & DevOps"},
    {"name": "GitHub Actions", "aliases": ["github actions ci", "gha"],                                      "category": "Cloud & DevOps"},
    {"name": "GitLab CI/CD",   "aliases": ["gitlab ci", "gitlab pipeline"],                                  "category": "Cloud & DevOps"},
    {"name": "CircleCI",       "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Travis CI",      "aliases": ["travisci"],                                                       "category": "Cloud & DevOps"},
    {"name": "CI/CD",          "aliases": ["continuous integration", "continuous deployment", "continuous delivery"], "category": "Cloud & DevOps"},
    {"name": "Prometheus",     "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Grafana",        "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "ELK Stack",      "aliases": ["elk", "logstash", "kibana"],                                     "category": "Cloud & DevOps"},
    {"name": "Nginx",          "aliases": ["nginx server"],                                                   "category": "Cloud & DevOps"},
    {"name": "Apache HTTP",    "aliases": ["apache httpd", "apache server"],                                  "category": "Cloud & DevOps"},
    {"name": "Linux",          "aliases": ["ubuntu", "debian", "centos", "rhel", "fedora", "arch linux", "linux admin"], "category": "Cloud & DevOps"},
    {"name": "Vagrant",        "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Packer",         "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "Helm",           "aliases": ["helm charts"],                                                    "category": "Cloud & DevOps"},
    {"name": "Istio",          "aliases": ["service mesh"],                                                   "category": "Cloud & DevOps"},
    {"name": "OpenShift",      "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "RabbitMQ",       "aliases": ["rabbitmq broker"],                                               "category": "Cloud & DevOps"},
    {"name": "Apache Kafka",   "aliases": ["kafka", "kafka streaming"],                                      "category": "Cloud & DevOps"},
    {"name": "Celery",         "aliases": [],                                                                  "category": "Cloud & DevOps"},
    {"name": "ArgoCD",         "aliases": ["argo cd", "gitops"],                                             "category": "Cloud & DevOps"},

    # ─── Data Science & Analytics ─────────────────────────────────────────
    {"name": "Machine Learning","aliases": ["ml", "machine learning algorithms"],                             "category": "Data Science & AI"},
    {"name": "Deep Learning",  "aliases": ["dl", "neural networks"],                                         "category": "Data Science & AI"},
    {"name": "NLP",            "aliases": ["natural language processing", "text mining", "text analytics"],  "category": "Data Science & AI"},
    {"name": "Computer Vision","aliases": ["cv", "image processing", "object detection"],                    "category": "Data Science & AI"},
    {"name": "TensorFlow",     "aliases": ["tensorflow 2", "tf", "tf2"],                                    "category": "Data Science & AI"},
    {"name": "PyTorch",        "aliases": ["torch"],                                                          "category": "Data Science & AI"},
    {"name": "Keras",          "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "scikit-learn",   "aliases": ["sklearn", "scikit learn"],                                       "category": "Data Science & AI"},
    {"name": "Hugging Face",   "aliases": ["huggingface", "transformers"],                                   "category": "Data Science & AI"},
    {"name": "OpenCV",         "aliases": ["cv2"],                                                            "category": "Data Science & AI"},
    {"name": "spaCy",          "aliases": ["spacy"],                                                          "category": "Data Science & AI"},
    {"name": "NLTK",           "aliases": ["natural language toolkit"],                                      "category": "Data Science & AI"},
    {"name": "XGBoost",        "aliases": ["xgb"],                                                           "category": "Data Science & AI"},
    {"name": "LightGBM",       "aliases": ["lgbm"],                                                          "category": "Data Science & AI"},
    {"name": "CatBoost",       "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Pandas",         "aliases": ["pandas dataframe"],                                              "category": "Data Science & AI"},
    {"name": "NumPy",          "aliases": ["numpy"],                                                          "category": "Data Science & AI"},
    {"name": "Matplotlib",     "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Seaborn",        "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Plotly",         "aliases": ["plotly dash", "dash"],                                           "category": "Data Science & AI"},
    {"name": "Jupyter",        "aliases": ["jupyter notebook", "jupyterlab", "ipynb"],                       "category": "Data Science & AI"},
    {"name": "Apache Spark",   "aliases": ["spark", "pyspark", "apache spark"],                              "category": "Data Science & AI"},
    {"name": "Hadoop",         "aliases": ["apache hadoop", "hdfs", "mapreduce"],                            "category": "Data Science & AI"},
    {"name": "Airflow",        "aliases": ["apache airflow"],                                                 "category": "Data Science & AI"},
    {"name": "dbt",            "aliases": ["dbt core", "data build tool"],                                   "category": "Data Science & AI"},
    {"name": "MLflow",         "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Kubeflow",       "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Statistics",     "aliases": ["statistical analysis", "statistical modeling", "probability and statistics", "probability"], "category": "Data Science & AI"},
    {"name": "Data Analysis",  "aliases": ["data analytics", "exploratory data analysis", "eda"],            "category": "Data Science & AI"},
    {"name": "Data Visualization", "aliases": ["data viz"],                                                  "category": "Data Science & AI"},
    {"name": "A/B Testing",    "aliases": ["ab testing", "hypothesis testing"],                              "category": "Data Science & AI"},
    {"name": "Feature Engineering", "aliases": [],                                                           "category": "Data Science & AI"},
    {"name": "Recommendation Systems", "aliases": ["recommender systems"],                                   "category": "Data Science & AI"},
    {"name": "Time Series Analysis", "aliases": ["time series"],                                             "category": "Data Science & AI"},
    {"name": "Generative AI",  "aliases": ["genai", "llm", "large language models", "chatgpt", "openai api", "langchain", "rag"], "category": "Data Science & AI"},
    {"name": "Tableau",        "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Power BI",       "aliases": ["powerbi", "microsoft power bi"],                                 "category": "Data Science & AI"},
    {"name": "Looker",         "aliases": [],                                                                  "category": "Data Science & AI"},
    {"name": "Qlik",           "aliases": ["qlikview", "qliksense"],                                         "category": "Data Science & AI"},

    # ─── Computer Science Fundamentals ────────────────────────────────────
    {"name": "Data Structures", "aliases": ["dsa", "data structures and algorithms", "ds&a"],                "category": "Computer Science"},
    {"name": "Algorithms",     "aliases": ["algorithm design", "competitive programming"],                   "category": "Computer Science"},
    {"name": "OOP",            "aliases": ["object oriented programming", "object-oriented design", "ooad"], "category": "Computer Science"},
    {"name": "System Design",  "aliases": ["systems design", "high level design", "hld", "low level design", "lld"], "category": "Computer Science"},
    {"name": "Design Patterns","aliases": ["software design patterns", "gang of four"],                      "category": "Computer Science"},
    {"name": "Distributed Systems", "aliases": ["distributed computing"],                                   "category": "Computer Science"},
    {"name": "Operating Systems", "aliases": ["os concepts"],                                                "category": "Computer Science"},
    {"name": "Computer Networks", "aliases": ["networking", "tcp/ip", "tcp ip", "network protocols"],       "category": "Computer Science"},
    {"name": "Database Management Systems", "aliases": ["dbms", "rdbms"],                                   "category": "Computer Science"},
    {"name": "Compiler Design","aliases": ["compilers"],                                                     "category": "Computer Science"},
    {"name": "Automata Theory","aliases": ["theory of computation"],                                        "category": "Computer Science"},

    # ─── Version Control & Collaboration ─────────────────────────────────
    {"name": "Git",            "aliases": ["git version control", "git workflow"],                           "category": "Tools & Platforms"},
    {"name": "GitHub",         "aliases": ["github.com"],                                                    "category": "Tools & Platforms"},
    {"name": "GitLab",         "aliases": ["gitlab.com"],                                                    "category": "Tools & Platforms"},
    {"name": "Bitbucket",      "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Jira",           "aliases": ["atlassian jira"],                                               "category": "Tools & Platforms"},
    {"name": "Confluence",     "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Trello",         "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Notion",         "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Slack",          "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "VS Code",        "aliases": ["visual studio code", "vscode"],                                  "category": "Tools & Platforms"},
    {"name": "IntelliJ IDEA",  "aliases": ["intellij", "idea"],                                             "category": "Tools & Platforms"},
    {"name": "Eclipse",        "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Postman",        "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Swagger",        "aliases": ["openapi", "swagger ui"],                                        "category": "Tools & Platforms"},
    {"name": "Figma",          "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "Excel",          "aliases": ["microsoft excel", "ms excel"],                                  "category": "Tools & Platforms"},
    {"name": "Linux Terminal", "aliases": ["command line", "cli", "terminal"],                               "category": "Tools & Platforms"},
    {"name": "Maven",          "aliases": ["apache maven"],                                                  "category": "Tools & Platforms"},
    {"name": "Gradle",         "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "npm",            "aliases": ["node package manager"],                                          "category": "Tools & Platforms"},
    {"name": "yarn",           "aliases": [],                                                                 "category": "Tools & Platforms"},
    {"name": "pip",            "aliases": ["python pip"],                                                    "category": "Tools & Platforms"},
    {"name": "Poetry",         "aliases": ["python poetry"],                                                 "category": "Tools & Platforms"},

    # ─── Testing & QA ─────────────────────────────────────────────────────
    {"name": "Unit Testing",   "aliases": ["unit tests", "tdd", "test driven development"],                  "category": "Testing & QA"},
    {"name": "Jest",           "aliases": ["jest testing"],                                                  "category": "Testing & QA"},
    {"name": "Pytest",         "aliases": ["pytest", "python testing"],                                      "category": "Testing & QA"},
    {"name": "JUnit",          "aliases": ["junit 5"],                                                       "category": "Testing & QA"},
    {"name": "Selenium",       "aliases": ["selenium webdriver"],                                            "category": "Testing & QA"},
    {"name": "Cypress",        "aliases": ["cypress.io"],                                                    "category": "Testing & QA"},
    {"name": "Playwright",     "aliases": [],                                                                 "category": "Testing & QA"},
    {"name": "Mocha",          "aliases": [],                                                                 "category": "Testing & QA"},
    {"name": "Chai",           "aliases": [],                                                                 "category": "Testing & QA"},
    {"name": "TestNG",         "aliases": [],                                                                 "category": "Testing & QA"},
    {"name": "Postman Testing","aliases": ["api testing"],                                                   "category": "Testing & QA"},
    {"name": "Load Testing",   "aliases": ["performance testing", "jmeter", "locust", "k6"],                "category": "Testing & QA"},
    {"name": "BDD",            "aliases": ["behavior driven development", "cucumber", "gherkin"],            "category": "Testing & QA"},

    # ─── Security ─────────────────────────────────────────────────────────
    {"name": "Cybersecurity",  "aliases": ["information security", "infosec", "cyber security"],             "category": "Security"},
    {"name": "Penetration Testing", "aliases": ["pentesting", "pen testing", "ethical hacking"],             "category": "Security"},
    {"name": "Network Security","aliases": [],                                                               "category": "Security"},
    {"name": "OWASP",          "aliases": ["owasp top 10"],                                                  "category": "Security"},
    {"name": "OAuth",          "aliases": ["oauth2", "oauth 2.0"],                                          "category": "Security"},
    {"name": "JWT",            "aliases": ["json web token"],                                                "category": "Security"},
    {"name": "SSL/TLS",        "aliases": ["ssl", "tls", "https"],                                          "category": "Security"},
    {"name": "Cryptography",   "aliases": ["encryption", "hashing"],                                        "category": "Security"},
    {"name": "Burp Suite",     "aliases": [],                                                                 "category": "Security"},
    {"name": "Metasploit",     "aliases": [],                                                                 "category": "Security"},
    {"name": "Wireshark",      "aliases": [],                                                                 "category": "Security"},
    {"name": "Nmap",           "aliases": [],                                                                 "category": "Security"},
    {"name": "SIEM",           "aliases": ["security information and event management"],                     "category": "Security"},

    # ─── Embedded & Hardware ──────────────────────────────────────────────
    {"name": "Embedded Systems","aliases": ["embedded c", "embedded programming"],                           "category": "Embedded & Hardware"},
    {"name": "Arduino",        "aliases": [],                                                                 "category": "Embedded & Hardware"},
    {"name": "Raspberry Pi",   "aliases": ["raspberrypi"],                                                   "category": "Embedded & Hardware"},
    {"name": "IoT",            "aliases": ["internet of things"],                                            "category": "Embedded & Hardware"},
    {"name": "RTOS",           "aliases": ["real time operating system", "freertos"],                        "category": "Embedded & Hardware"},
    {"name": "VLSI",           "aliases": ["vlsi design"],                                                   "category": "Embedded & Hardware"},
    {"name": "PCB Design",     "aliases": ["printed circuit board"],                                         "category": "Embedded & Hardware"},
    {"name": "Signal Processing","aliases": ["dsp", "digital signal processing"],                            "category": "Embedded & Hardware"},
    {"name": "PLC",            "aliases": ["programmable logic controller"],                                 "category": "Embedded & Hardware"},
    {"name": "Microcontrollers","aliases": ["stm32", "avr", "pic microcontroller"],                         "category": "Embedded & Hardware"},
    {"name": "FPGA",           "aliases": ["field programmable gate array"],                                 "category": "Embedded & Hardware"},
    {"name": "AutoCAD",        "aliases": ["autocad design"],                                               "category": "Embedded & Hardware"},
    {"name": "SolidWorks",     "aliases": ["solidworks cad"],                                               "category": "Embedded & Hardware"},
    {"name": "LabVIEW",        "aliases": [],                                                                 "category": "Embedded & Hardware"},

    # ─── Design & UI/UX ───────────────────────────────────────────────────
    {"name": "UI/UX Design",   "aliases": ["ui design", "ux design", "user interface", "user experience"],  "category": "Design"},
    {"name": "Figma",          "aliases": [],                                                                 "category": "Design"},
    {"name": "Adobe XD",       "aliases": ["xd"],                                                            "category": "Design"},
    {"name": "Sketch",         "aliases": [],                                                                 "category": "Design"},
    {"name": "Adobe Photoshop","aliases": ["photoshop"],                                                     "category": "Design"},
    {"name": "Adobe Illustrator","aliases": ["illustrator"],                                                 "category": "Design"},
    {"name": "InVision",       "aliases": [],                                                                 "category": "Design"},
    {"name": "Wireframing",    "aliases": ["prototyping"],                                                   "category": "Design"},
    {"name": "Responsive Design","aliases": ["mobile-first design"],                                        "category": "Design"},

    # ─── Project Management & Methodologies ────────────────────────────────
    {"name": "Agile",          "aliases": ["agile methodology", "agile development"],                        "category": "Methodologies"},
    {"name": "Scrum",          "aliases": ["scrum master", "scrum methodology"],                             "category": "Methodologies"},
    {"name": "Kanban",         "aliases": [],                                                                 "category": "Methodologies"},
    {"name": "DevOps",         "aliases": ["devops practices"],                                              "category": "Methodologies"},
    {"name": "SDLC",           "aliases": ["software development lifecycle"],                                "category": "Methodologies"},
    {"name": "Waterfall",      "aliases": ["waterfall model"],                                               "category": "Methodologies"},
    {"name": "SAFe",           "aliases": ["scaled agile framework"],                                        "category": "Methodologies"},
    {"name": "PRINCE2",        "aliases": [],                                                                 "category": "Methodologies"},

    # ─── Soft Skills ──────────────────────────────────────────────────────
    {"name": "Communication",  "aliases": ["verbal communication", "written communication", "presentation skills"], "category": "Soft Skills"},
    {"name": "Leadership",     "aliases": ["team leadership", "people management"],                          "category": "Soft Skills"},
    {"name": "Teamwork",       "aliases": ["collaboration", "team player", "cross-functional"],              "category": "Soft Skills"},
    {"name": "Problem Solving","aliases": ["analytical thinking", "critical thinking", "problem-solving"],  "category": "Soft Skills"},
    {"name": "Time Management","aliases": ["deadline management"],                                           "category": "Soft Skills"},
    {"name": "Adaptability",   "aliases": ["flexibility"],                                                   "category": "Soft Skills"},
    {"name": "Mentoring",      "aliases": ["coaching", "knowledge transfer"],                               "category": "Soft Skills"},
    {"name": "Research",       "aliases": ["research skills"],                                               "category": "Soft Skills"},
    {"name": "Public Speaking","aliases": ["presentations"],                                                 "category": "Soft Skills"},

    # ─── Domain / Industry ────────────────────────────────────────────────
    {"name": "Blockchain",     "aliases": ["ethereum", "solidity", "web3", "smart contracts", "dapp"],      "category": "Domain Knowledge"},
    {"name": "FinTech",        "aliases": ["financial technology", "payment systems"],                       "category": "Domain Knowledge"},
    {"name": "E-commerce",     "aliases": ["ecommerce"],                                                     "category": "Domain Knowledge"},
    {"name": "Healthcare IT",  "aliases": ["health informatics", "hl7", "fhir"],                            "category": "Domain Knowledge"},
    {"name": "ERP Systems",    "aliases": ["sap", "oracle erp", "salesforce"],                              "category": "Domain Knowledge"},
    {"name": "Digital Marketing","aliases": ["seo", "sem", "google analytics"],                              "category": "Domain Knowledge"},
    {"name": "Game Development","aliases": ["unity", "unreal engine", "godot", "pygame"],                   "category": "Domain Knowledge"},
    {"name": "Robotics",       "aliases": ["ros", "robot operating system"],                                "category": "Domain Knowledge"},
    {"name": "Quantum Computing","aliases": ["qiskit"],                                                      "category": "Domain Knowledge"},
    {"name": "Augmented Reality","aliases": ["ar", "ar development", "arkit", "arcore"],                   "category": "Domain Knowledge"},
    {"name": "Virtual Reality","aliases": ["vr", "vr development"],                                         "category": "Domain Knowledge"},
]

# ─── Build lookup tables ──────────────────────────────────────────────────────

# alias (lowercase) → canonical name
ALIAS_TO_CANONICAL: dict = {}
# canonical name → category
CANONICAL_TO_CATEGORY: dict = {}
# category → list of canonical skill names
CATEGORY_TO_SKILLS: dict = {}

for entry in SKILLS:
    canonical = entry["name"]
    category  = entry["category"]

    CANONICAL_TO_CATEGORY[canonical] = category
    CATEGORY_TO_SKILLS.setdefault(category, []).append(canonical)

    # Index canonical name itself (lowercase)
    ALIAS_TO_CANONICAL[canonical.lower()] = canonical

    # Index all aliases
    for alias in entry.get("aliases", []):
        ALIAS_TO_CANONICAL[alias.lower()] = canonical


ALL_CATEGORIES = list(CATEGORY_TO_SKILLS.keys())
TOTAL_SKILLS   = len(SKILLS)
